<?php
// $Id$

/**
 * @file
 *  Boxes Example module. Declares existing of boxes plugins.
 */

/**
 * Implementation of hook_ctools_plugin_api().
 */
function boxes_example_ctools_plugin_api($module, $api) {
  if ($module == 'boxes' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_boxes_plugins().
 */
function boxes_example_boxes_plugins() {
  $info = array();
  $path = drupal_get_path('module', 'boxes_example') . '/plugins';
  $info['views_simple'] = array(
    // The title is what makes this a box that site-builders can use.
    'title' => 'Views Box',
    'handler' => array(
      // All boxes must extend the 'box' or one of its descendents.
      'parent' => 'box',
      'class' => 'boxes_example_boxes_views_simple',
      'file' => 'boxes_example_boxes_views_simple.inc',
      'path' => $path,
    ),
  );
  return $info;
}
